[package]
name = "gpui-play"
version = "0.1.0"
description = "Playing around with GPUI and components by that team that brought us Zed Editor."

edition.workspace = true
license.workspace = true

authors.workspace = true
homepage.workspace = true
repository.workspace = true


[dependencies]
env_logger.workspace = true
log.workspace = true


[dependencies.anyhow]
version = "1.0"
default-features = false
features = []

[dependencies.gpui]
version = "0.2.2"
default-features = false
features = ["font-kit"]

# [dependencies.gpui-component]
# version = "0.3.1"
# default-features = false
# features = []

