[package]
name = "bevy-play"
version = "0.1.0"
edition = "2024"

description = "Playing with Bevy again."
license = "MIT"

authors = [ "Robert Anderson (https://shiftylogic.dev)" ]
homepage = "https://www.shiftylogic.com"
repository = "https://github.com/shiftylogic/<update with repo>/demos/bevy-play"


[dependencies]
env_logger.workspace = true
log.workspace = true


[dependencies.bevy]
version = "0.17.2"
default-features = false
features = [
    # Runtime components
    "std",                              # [platform]
    #"async-io",
    "async_executor",                   # [app]
    "multi_threaded",                   # [platform]

    # Core Functionality
    #"asset_processor",
    #"bevy_animation",
    #"bevy_asset",                       # [app]
    #"bevy_color",
    #"bevy_core_pipeline",               # Rendering pipeline
    #"bevy_gilrs",                       # [app] Gamepad
    #"bevy_input_focus",                 # [app]
    #"bevy_light",                       # Point, directional, spotlights
    "bevy_log",                         # [app]
    #"bevy_post_process",                # DoF, Bloom, chromatic aberration, etc.
    #"bevy_remote",                      # Remote protocol
    #"bevy_render",
    #"bevy_scene",
    #"bevy_shader",
    #"bevy_solari",                      # Raytracing (experimental)
    #"bevy_sprite",
    #"bevy_sprite_render",
    "bevy_state",                       # [app] Global (built-in) state machine
    #"bevy_text",

    # Anti-aliasing
    #"bevy_anti_alias",
    #"dlss",

    # Audio
    #"bevy_audio",
    #"flac",
    #"mp3",
    #"vorbis",
    #"wav",
    #"symphonia-all",                    # AAC, FLAC, MP3, MP4, OGG/Vorbis, WAV (through Symphonia)
    #"symphonia-aac",
    #"symphonia-flac",
    #"symphonia-ispmp4",
    #"symphonia-vorbis",
    #"symphonia-wav",

    # Cameras
    #"bevy_camera",
    #"bevy_camera_controller",           # All built-in camera controllers
    #"free_camera",
    #"pan_camera",

    # Image Support
    #"bevy_image",
    #"bmp",
    #"dds",
    #"exr",
    #"ff",
    #"gif",
    #"hdr",
    #"ico",
    #"jpeg",
    #"ktx2",
    #"png",
    #"pnm",                              # PAM, PBM, PGM, PPM
    #"qoi",
    #"tga",
    #"tiff",
    #"webp",
    #"smaa_luts",                        # Lookup Tables for KTX2 files
    #"tonemapping_luts",                 # Lookup Tables for KTX2 files
    #"xlib",                             # KTX2 super-compression
    #"zstd_c",                           # Faster but "unsafe" C bindings
    #"zstd_rust",                        # "Safe" pure rust, but slower

    # Models
    #"bevy_gltf",
    #"bevy_mesh",
    #"bevy_mikktspace",                  # Vertex tangent generation (with bevy_mesh)
    #"gltf_animation",
    #"morph",                            # Morph target weights (with bevy_mesh)
    #"morph_animation",

    # Object picking
    #"bevy_picking",
    #"mesh_picking",
    #"sprite_picking",
    #"ui_picking",

    # PBR
    #"bevy_pbr",
    #"experimental_pbr_pcss",            # Will cause issues on older hardware
    #"meshlet",                          # Dense high-poly scenes (experimental)
    #"meshlet_processor",                # Meshes to meshlets for PBR
    #"pbr_anisotropy_texture",           # Careful on low-end hardware
    #"pbr_clustered_decals",
    #"pbr_light_textures",
    #"pbr_multi_layer_material_textures",
    #"pbr_specular_textures",
    #"pbr_transmission_textures",

    # Reflect
    #"reflect_auto_register",
    #"reflect_auto_register_static",
    #"reflect_documentation",
    #"reflect_functions",

    # Shaders
    #"shader_format_glsl",
    #"shader_format_spirv",
    #"shader_format_wesl",
    #"spirv_shader_passthrough",         # Vulkan only
    #"statically-linked-dxc",            # DirectX 12

    # User Interface & widgets
    #"bevy_gizmos",
    #"bevy_gizmos_render",
    #"bevy_ui",
    #"bevy_ui_render",
    #"experimental_bevy_feathers",       # Experimental
    #"experimental_bevy_ui_widgets",     # Experimental

    # Vulkan
    #"raw_vulkan_init",                  # Advanced Vulkan configuration

    # Web / WASM
    #"web",                              # Browser APIs
    #"web_asset_cache",                  # [2025-10-21] Currently never invalidates entries!
    #"webgl2",
    #"webgpu",                           # Overrides webgl2

    # Windowing
    "bevy_window",                      # [app]
    "bevy_winit",                       # [platform]
    #"custom_cursor",                    # [app] Requires bevy_winit
    #"wayland",
    #"x11",

    # Other
    "default_font",                     # [platform] Built-in (ASCII only) font
    #"embedded_watcher",                 # Watch in-memory assets (hot-reload)
    #"file_watcher",                     # Watch asset files (hot-reload)
    #"libm",                             # Math library (replaces std and core)
    #"serialize",                        # via Serde
    "sysinfo_plugin",                   # System diagnostics

    # Development / Debugging
    #"bevy_debug_stepping",
    "bevy_dev_tools",
    #"bevy_ui_debug",
    "debug",
    #"debug_glam_assert",
    #"detailed_trace",
    "dynamic_linking",                  # Binary size smaller, but requires multiple files (faster 'dev' compile)
    #"glam_assert",
    #"hotpatching",
    #"trace",
    #"trace_chrome",
    #"trace_tracy",
    #"trace_tracy_memory",
    #"track_location",
]

